// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface ICodeToolFields {
  /** Name */
  name: string;

  /** Description */
  description?: string | undefined;

  /** Image */
  image: Asset;
}

export interface ICodeTool extends Entry<ICodeToolFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "codeTool";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPromoFields {
  /** Promo text */
  promoText?: string | undefined;

  /** promo image */
  promoImage: Asset;
}

export interface IPromo extends Entry<IPromoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "promo";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "codeTool" | "promo";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
